//
//  RPSAPIConst.h
//  ReservedParkingSpace
//
//  Created by Administrator on 2019/1/15.
//  Copyright © 2019 yunqwi. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


NS_ASSUME_NONNULL_BEGIN

typedef NSString * RPSSERVER_API;

UIKIT_EXTERN RPSSERVER_API const STRTELPHONE;
UIKIT_EXTERN RPSSERVER_API const ENTERPRISE_SERVER_HOST;    //服务器地址
UIKIT_EXTERN RPSSERVER_API const NET_SERVER_HOST;  //2.8版本新增服务器地址
UIKIT_EXTERN RPSSERVER_API const CAPTCHA;            //获取验证码
UIKIT_EXTERN RPSSERVER_API const ENTERPRISE_LOGIN_URL;         //登录
UIKIT_EXTERN RPSSERVER_API const ENTERPRISE_MAIN_NUM_URL;
UIKIT_EXTERN RPSSERVER_API const ENTERPRISE_USERID;
UIKIT_EXTERN RPSSERVER_API const ENTERPRISE_PARENTID;
UIKIT_EXTERN RPSSERVER_API const ENTERPRISE_BROWSETYPE;
UIKIT_EXTERN RPSSERVER_API const ENTERPRISE_REGISTER_CODE_URL;
UIKIT_EXTERN RPSSERVER_API const ENTERPRISE_REGISTER_URL;
UIKIT_EXTERN RPSSERVER_API const ENTERPRISE_PERSON_URL;
UIKIT_EXTERN RPSSERVER_API const ENTERPRISE_WAIT_ORDER_LIST_URL;
UIKIT_EXTERN RPSSERVER_API const WAIT_ORDER_DETAIL_URL;
UIKIT_EXTERN RPSSERVER_API const WAIT_ORDER_ITEM_DETAIL_URL;
UIKIT_EXTERN RPSSERVER_API const INSRTALL_ORDER_ITEM_DETAIL_URL;
UIKIT_EXTERN RPSSERVER_API const WAIT_ORDER_ACCEPT_URL;
UIKIT_EXTERN RPSSERVER_API const ORDER_PICTURE_URL;
UIKIT_EXTERN RPSSERVER_API const NOTICE_LIST_URL;
UIKIT_EXTERN RPSSERVER_API const WALLET_NO_PAY_LIST_URL;
UIKIT_EXTERN RPSSERVER_API const UPLOAD_PICTURE_URL;
UIKIT_EXTERN RPSSERVER_API const INSTALL_ORDER_LIST_URL;
UIKIT_EXTERN RPSSERVER_API const GRAB_ORDER_LIST_URL;
UIKIT_EXTERN RPSSERVER_API const RELEASE_SUBMIT_URL;
UIKIT_EXTERN RPSSERVER_API const RELEASE_PERSON_URL;
UIKIT_EXTERN RPSSERVER_API const WALLET_TRIAL_URL;
UIKIT_EXTERN RPSSERVER_API const WALLET_HAVE_PAY_URL;
UIKIT_EXTERN RPSSERVER_API const ENTERPRISE_CONST_PROTOCOL_URL;
UIKIT_EXTERN RPSSERVER_API const ENTERPRISE_CONST_PROTOCOL_01_URL;
UIKIT_EXTERN RPSSERVER_API const MODIFY_PASSWORD_URL;
UIKIT_EXTERN RPSSERVER_API const APPLY_PAY_URL;
UIKIT_EXTERN RPSSERVER_API const PAY_RATE_URL;
UIKIT_EXTERN RPSSERVER_API const WITHDRAW_URL;
UIKIT_EXTERN RPSSERVER_API const EDIT_PERSON_MODIFY_URL;
UIKIT_EXTERN RPSSERVER_API const APPLY_PAY_DETAIL_URL;
UIKIT_EXTERN RPSSERVER_API const INSTALL_ORDER_STATISTIC_LIST_URL;
UIKIT_EXTERN RPSSERVER_API const BRAND_LIST_URL;
UIKIT_EXTERN RPSSERVER_API const BRAND_LIST_DETAIL_URL;
UIKIT_EXTERN RPSSERVER_API const RELEASE_LIST_URL;
UIKIT_EXTERN RPSSERVER_API const INSTALL_TYPE_URL;
UIKIT_EXTERN RPSSERVER_API const RELEASE_ITEM_LIST_URL;
UIKIT_EXTERN RPSSERVER_API const RELEASE_CANCEL_URL;
UIKIT_EXTERN RPSSERVER_API const RELEASE_CONFIRM_MASTER_URL;
UIKIT_EXTERN RPSSERVER_API const ADDRESS_URL;
UIKIT_EXTERN RPSSERVER_API const WE_CHAT_APPID;
UIKIT_EXTERN RPSSERVER_API const ENTERPRISE_SERVER_OTHER_HOST;//人脸识别地址
UIKIT_EXTERN RPSSERVER_API const PAY_URL;
UIKIT_EXTERN RPSSERVER_API const UNIVERSAL_LINK;
UIKIT_EXTERN RPSSERVER_API const ORDER_INFO_URL;
UIKIT_EXTERN RPSSERVER_API const ORDER_EDIT_INFO_URL;
UIKIT_EXTERN RPSSERVER_API const ORDER_EDIT_SUBMIT_URL;
UIKIT_EXTERN RPSSERVER_API const ORDER_MESSAGE_URL;
UIKIT_EXTERN RPSSERVER_API const ORDER_MESSAGE_INFO_URL;
UIKIT_EXTERN RPSSERVER_API const PASSWORD_INFO_URL;
UIKIT_EXTERN RPSSERVER_API const CASE_LIST_URL;
UIKIT_EXTERN RPSSERVER_API const ADD_COMPLAIN_URL;
UIKIT_EXTERN RPSSERVER_API const MODIFY_COMPLAIN_URL;
NS_ASSUME_NONNULL_END
